### ISSUE TITLE
FileNotFound Warning

### ISSUE THREAD

**Issue by arcas0803** [Tobiaswk/scheduled_notifications#1]
`W/System.err(28295): java.io.FileNotFoundException: /data/user/0/com.yourcompany.irri/files/scheduledNotifications (No such file or directory)
W/System.err(28295): 	at java.io.FileInputStream.open(Native Method)
W/System.err(28295): 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
W/System.err(28295): 	at android.app.ContextImpl.openFileInput(ContextImpl.java:476)
W/System.err(28295): 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:186)
W/System.err(28295): 	at dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager.load(ScheduleNotificationsManager.java:59)
W/System.err(28295): 	at dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager.instance(ScheduleNotificationsManager.java:91)
W/System.err(28295): 	at dk.kjeldsen.scheduled_notifications.ScheduledNotificationsPlugin.scheduledNotification(ScheduledNotificationsPlugin.java:49)
W/System.err(28295): 	at dk.kjeldsen.scheduled_notifications.ScheduledNotificationsPlugin.onMethodCall(ScheduledNotificationsPlugin.java:36)
W/System.err(28295): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
W/System.err(28295): 	at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:643)
W/System.err(28295): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(28295): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(28295): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(28295): 	at android.app.ActivityThread.main(ActivityThread.java:6126)
W/System.err(28295): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(28295): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err(28295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

But works perfect.
Is possible to use this to build real notifications?

**Comment by Tobiaswk** [comment]
Yes this exception should caught and handled. I'll fix it tomorrow. It happens the first time a notification is registered. The internal list that holds notifications haven't been serialized to a file and thus no internal file is present. It does not have any effect on the functionality like you state.

What do you mean by _real notifications_? This does build native notifications on Android. So it is _real_ in that sense.
