### ISSUE TITLE
Unregister notification!

### ISSUE THREAD

**Issue by welldone217** [Tobiaswk/scheduled_notifications#3]
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Register notification!
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Saved scheduled notification!
I/flutter ( 4938): 1783802548
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsService( 4938): Service start
D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Unregister notification!

what i can do?

**Comment by Tobiaswk** [comment]
@welldone217 I'm not entirely sure what you problem is? It seems to me that it is working as intended.

**Comment by Tobiaswk** [comment]
Closing this issue. No feedback.

**Comment by Stnieder** [comment]
I do have the problem as @welldone217. In the console everything runs fine, but there is no notification showing up.

**Comment by stnieder** [comment]
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Register notification!
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Saved scheduled notification!
> I/flutter ( 4938): 1783802548
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsService( 4938): Service start
> D/dk.kjeldsen.scheduled_notifications.ScheduleNotificationsManager( 4938): Unregister notification!
> 
> what i can do?

I do have the problem as @welldone217. In the console everything runs fine, but there is no notification showing up.

**Comment by tusharpandey** [comment]
Yes same in my case, no notification.

**Comment by Fabio91** [comment]
Same in my case, no notification.

**Comment by feliciaeponou** [comment]
Hello ! Have you found a solution ? I am facing the same issue.

**Comment by Tobiaswk** [comment]
This package is not maintained any longer.

Den 29. marts 2021 11.43.57 CEST, Felicia Eponou ***@***.***> skrev:
